# Generated by Django 4.2.7 on 2023-11-20 07:25

from django.db import migrations, models
import django.db.migrations.operations.special
import django.utils.timezone
import uuid


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# imageRater.migrations.0011_createsuperuser
# imageRater.migrations.0013_auto_20231108_1824
# imageRater.migrations.0018_auto_20231120_0059
# imageRater.migrations.0020_auto_20231120_0146

class Migration(migrations.Migration):

    replaces = [('imageRater', '0001_initial'), ('imageRater', '0002_alter_imagerating_image'), ('imageRater', '0003_imagerating_rating'), ('imageRater', '0004_alter_imagerating_rating'), ('imageRater', '0005_alter_imagerating_rating'), ('imageRater', '0006_alter_imagerating_rating'), ('imageRater', '0007_alter_imagerating_rating'), ('imageRater', '0008_alter_imagerating_rating'), ('imageRater', '0009_alter_imagerating_rating'), ('imageRater', '0010_alter_imagerating_rating'), ('imageRater', '0011_createsuperuser'), ('imageRater', '0012_imagerating_uuid'), ('imageRater', '0013_auto_20231108_1824'), ('imageRater', '0014_auto_20231108_1824'), ('imageRater', '0015_remove_imagerating_id_alter_imagerating_uuid'), ('imageRater', '0016_imagerating_created_at_imagerating_updated_at_and_more'), ('imageRater', '0017_auto_20231120_0056'), ('imageRater', '0018_auto_20231120_0059'), ('imageRater', '0019_auto_20231120_0146'), ('imageRater', '0020_auto_20231120_0146'), ('imageRater', '0021_remove_imagerating_rating'), ('imageRater', '0022_alter_imagerating_rated_img_name_and_more'), ('imageRater', '0023_alter_imagerating_rated_img_name_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('rating', models.JSONField(default=dict)),
            ],
        ),
        migrations.RunPython(code="imageRater.migrations.0011_createsuperuser.createsuperuser"),
        migrations.AddField(
            model_name='imagerating',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.RunPython(
            code=imageRater.migrations.0013_auto_20231108_1824.gen_uuid,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='imagerating',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.RemoveField(
            model_name='imagerating',
            name='id',
        ),
        migrations.AlterField(
            model_name='imagerating',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='imagerating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagerating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='imagerating',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AddField(
            model_name='imagerating',
            name='rating_obj',
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(
            code=imageRater.migrations.0018_auto_20231120_0059.convert_to_rating_obj,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='imagerating',
            name='rated_img_name',
            field=models.CharField(default=str),
        ),
        migrations.AddField(
            model_name='imagerating',
            name='rated_value',
            field=models.FloatField(default=float),
        ),
        migrations.AddField(
            model_name='imagerating',
            name='url',
            field=models.URLField(default=str),
        ),
        migrations.RunPython(
            code=imageRater.migrations.0020_auto_20231120_0146.gen_names,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=imageRater.migrations.0020_auto_20231120_0146.gen_ratings,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='imagerating',
            name='rating',
        ),
        migrations.AlterField(
            model_name='imagerating',
            name='rated_img_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='imagerating',
            name='rated_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='imagerating',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='imagerating',
            name='rated_img_name',
            field=models.CharField(default=str),
        ),
        migrations.AlterField(
            model_name='imagerating',
            name='rated_value',
            field=models.FloatField(default=float),
        ),
        migrations.AlterField(
            model_name='imagerating',
            name='url',
            field=models.URLField(default=str),
        ),
    ]
