# Generated by Django 4.2.6 on 2023-10-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageRater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerating',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
