# Generated by Django 4.2.6 on 2023-10-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageRater', '0002_alter_imagerating_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerating',
            name='rating',
            field=models.JSONField(default=str),
            preserve_default=False,
        ),
    ]
