# Generated by Django 4.2.7 on 2023-11-08 23:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('imageRater', '0011_createsuperuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerating',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
