# Generated by Django 4.2.7 on 2023-11-08 23:24

import uuid
from django.db import migrations,models


class Migration(migrations.Migration):
    dependencies = [
        ("imageRater", "0013_auto_20231108_1824"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagerating",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
