# Generated by Django 4.2.7 on 2023-11-08 23:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('imageRater', '0014_auto_20231108_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagerating',
            name='id',
        ),
        migrations.AlterField(
            model_name='imagerating',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
