# Generated by Django 4.2.7 on 2023-11-14 04:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imageRater', '0015_remove_imagerating_id_alter_imagerating_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagerating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='imagerating',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
