# Generated by Django 4.2.7 on 2023-11-20 05:59

import logging
from django.db import migrations

logger = logging.getLogger(__file__)


def convert_to_rating_obj(apps, schema_editor):
    ImageRating = apps.get_model("imageRater", "imagerating")
    for row in ImageRating.objects.all():
        row.rating_obj = row.rating
        row.save(update_fields=["rating_obj"])


class Migration(migrations.Migration):
    dependencies = [
        ("imageRater", "0017_auto_20231120_0056"),
    ]

    operations = [
        migrations.RunPython(
            convert_to_rating_obj, reverse_code=migrations.RunPython.noop
        ),
    ]
