# Generated by Django 4.2.7 on 2023-11-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imageRater", "0018_auto_20231120_0059"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagerating",
            name="rated_img_name",
            field=models.CharField(default=str),
        ),
        migrations.AddField(
            model_name="imagerating",
            name="rated_value",
            field=models.FloatField(default=float),
        ),
        migrations.AddField(
            model_name="imagerating",
            name="url",
            field=models.URLField(default=str),
        ),
    ]
