# Generated by Django 4.2.7 on 2023-11-20 06:46

import logging
from django.db import migrations

logger = logging.getLogger(__file__)


def gen_names(apps, schema_editor):
    ImageRating = apps.get_model("imageRater", "imagerating")
    for row in ImageRating.objects.all():
        for x in row.rating:
            if x != None:
                logger.debug(f"name: {x}")
                row.rated_img_name = x
                row.url = x
            else:
                row.rated_img_name = "default"
                row.url = "https://www.google.com"
        row.save()


def gen_ratings(apps, schema_editor):
    ImageRating = apps.get_model("imageRater", "imagerating")
    for row in ImageRating.objects.all():
        for x in row.rating:
            row.rated_value = row.rating.get(x)
        row.save(update_fields=["rated_value"])


class Migration(migrations.Migration):
    dependencies = [
        ("imageRater", "0019_auto_20231120_0146"),
    ]

    operations = [
        migrations.RunPython(gen_names, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(gen_ratings, reverse_code=migrations.RunPython.noop),
    ]
