# Generated by Django 4.2.7 on 2023-11-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageRater', '0022_alter_imagerating_rated_img_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerating',
            name='rated_img_name',
            field=models.CharField(default=str),
        ),
        migrations.AlterField(
            model_name='imagerating',
            name='rated_value',
            field=models.FloatField(default=float),
        ),
        migrations.AlterField(
            model_name='imagerating',
            name='url',
            field=models.URLField(default=str),
        ),
    ]
